### ISSUE TITLE
Reuse existing connection

### ISSUE THREAD

**Issue by jasonlfunk** [spatie/browsershot#122]
I have a tool that needs to use Browsershot multiple times to load various webpages. As I understand it, every time I call `bodyHtml` it loads a new instance of Pupetteer and Chrome. Is there a way to reuse the existing connection? It appears that puppetter supports this:
https://github.com/GoogleChrome/puppeteer/blob/master/docs/api.md#puppeteerconnectoptions

**Comment by barryvdh** [comment]
You should be able to, but I think you need to get the WSEndpoint from webSocketDebuggerUrl on `http://127.0.0.1:9222/json/version` and connect to that.
But it would probably be hard to get reliable, as you'd need to detect if it's running, otherwise launch a in daemon mode etc.

Are you loading them in the same request? Cause it would perhaps be easier to modify the script to accept multiple input/output parameters, so you could process multiple pages in the same Puppeteer command.
Perhaps even with parallelisation: https://github.com/GoogleChrome/puppeteer/issues/471

**Comment by jasonlfunk** [comment]
Handling multiple pages in a single request wouldn't be ideal, but it would be an improvement on what I have now. Thanks for the feedback. If I do make any changes, I'll be sure to make a PR.

**Comment by BorderCloud** [comment]
I have the same need. I do a lot screenshots on a server. 
I would prefer to leave the browser open between each screenshot to speed up the execution time.
It's possible in the doc of puppetteer :
https://developers.google.com/web/tools/puppeteer/articles/ssr#reuseinstance

Thanks and good job for Browsershot !

**Comment by freekmurze** [comment]
@BorderCloud If you need this feel free to PR this (with tests and an updated readme)
