### ISSUE TITLE
I can't make it working on Windows…

### ISSUE THREAD

**Issue by julien-garand** [spatie/browsershot#149]
Do you think it could be possible to make browsershot working on a windows web server ?

I tried for a few hours now and didn't manage… Thanks for your help.

**Comment by freekmurze** [comment]
I'm not a Windows user, so I'm not going to invest time in this.

If you find a solution, and it's a simple code change, feel free to PR a fix.

**Comment by julien-garand** [comment]
I'm not a windows user too. So…

**Comment by filipegar** [comment]
@freekmurze I think I managed a way to get it working on windows but would require to change the function callBrowser a little.

The main problem I could track is with the args passed to the binary.js file. For some reason, the JSON string is misunderstood and the process dies because could not parse JSON.

My environment does have node, npm, puppeteer on PATH, but for the script-scope it would better have some different options to set Windows PATH and the other properties - the calls on windows cmd are a little different than linux ([here](https://stackoverflow.com/questions/6832496/command-prompt-how-to-add-a-set-path-only-for-that-batch-file-executing)).

Do you think it is worth a pull-request here? What would be the best approch? I want to collaborate here but I don't want to break everything else.

```
`
protected function callBrowser(array $command)
    {
        $setIncludePathCommand = "PATH={$this->includePath}";

        $nodeBinary = $this->nodeBinary ?: 'node';

        $setNodePathCommand = $this->getNodePathCommand($nodeBinary);

        $binPath = __DIR__.'\..\bin\browser.js';

        $fullCommand =
            $nodeBinary.' '
            .escapeshellarg($binPath).' '
            . '"'. str_replace('"', '""',  json_encode($command)) . '"';

        $process = (new Process($fullCommand))->setTimeout($this->timeout);

        $process->run();

        if (! $process->isSuccessful()) {
            throw new ProcessFailedException($process);
        }

        return $process->getOutput();
    }`
```

**Comment by danhunsaker** [comment]
Any PR would need to detect the OS, and then use the correct code for the current one in either case. Meaning instead of replacing the code that works in *NIX systems, wrap it in an `if ... else` that checks for Windows, and drop the Windows-specific changes in the other logic path.

Of course, OS-specific code will negatively impact code coverage scores.

**Comment by oppure** [comment]
Hi
I'm trying to use browsershot on a development machine with windows 10 64 and xampp v3.2.2 php 7.1
To make it short it works ok only if I unset the TMP variable (either in Process::start code or in the  httpd-xampp.conf file). It seems that when puppeteer is able to write to temp dir (so it can create a dev-profiles-... dir) the process timeout without downloading any html, no error logged in sf_proc_00.err, no errors from php, chrome is launched but it doesn't seem to connect to any external website. When there is no tmp dir available I get the html body code correctly.
Can someone give me any clue on how to continue debugging this? I've no idea anymore.
Thank you.
