### ISSUE TITLE
Cannot get browsershot to work

### ISSUE THREAD

**Issue by donaldtbd** [spatie/browsershot#164]
Im trying to set up browsershot in laravel 5.4 to take a screenshot of a web page. I followed the instructions here: https://github.com/spatie/browsershot

So first i ran commands:
npm install puppeteer
composer require spatie/browsershot

And then in my code:
use Spatie\Browsershot\Browsershot;
dd(Browsershot::url('https://example.com')->screenshot());

But this just returns a empty string. Because there is no further feedback i dont know what else to try.

My setup is windows 10, php 7.2.2, node v8.9.4 and npm 5.6.0.

**Comment by riksnelders** [comment]
Same problem here.

**Comment by MENtechmedia** [comment]
Same problem here

**Comment by danhunsaker** [comment]
Markdown is supported in GitHub issues and comments; you can save yourself a good deal of headache by learning and using it.

That said, are you running the exact code given above? Attempting a request to `https://example.com`? Because that's guaranteed never to work - the domain specs explicitly forbid registration of `example.*`, so it will never resolve to an actual page. So you should definitely at least switch out that URL for one that will actually work (say, `https://github.com`, as just one option).

If that doesn't fix it, we'll need more data to be any actual help.
