### ISSUE TITLE
How to run browsershot

### ISSUE THREAD

**Issue by edenisn** [spatie/browsershot#238]
Can you please write step by step what I need to do to run php scripts from your README?
I am confuse. I create file test.php:
```
<?php
use Spatie\Browsershot\Browsershot;

// an image will be saved
Browsershot::url('http://test.com')
   ->save('./test.png);
?>
```
then run this file from terminal with command: php test.php and got error:
```
Fatal error: Class 'Browsershot' not found 
```
Thanks!

**Comment by danhunsaker** [comment]
Well, yes, you haven't actually loaded the class at all, have you?

When a project uses Composer - as this one does - part of what that means is that your projects will need to include the Composer autoloader at some point so PHP knows what the classes and so forth you're trying to use actually are. That step isn't mentioned here, or essentially _anywhere_ Composer is used to install a package, because it's part of using Composer itself.

For more details, look up how to use Composer itself.
