### ISSUE TITLE
Node error on Forge provisioned server

### ISSUE THREAD

**Issue by peteheaney** [spatie/browsershot#245]
Hi

I'm using Browsershot with Laravel. I have it running perfectly in my local dev environment (Mac, Laravel Valet), but when running it on a Forge provisioned server, I get the following error in my log file (I've replaced sensitive URLs with placeholders):

```
local.ERROR: The command "PATH=$PATH:/usr/local/bin NODE_PATH=`/usr/bin/node /usr/bin/npm root -g` /usr/bin/node '/home/forge/my-app.co.uk/vendor/spatie/browsershot/src/../bin/browser.js' '{"url":"https:\/\/my-test-site.com\/about.html","action":"screenshot","options":{"type":"png","path":"\/home\/forge\/my-app.com\/storage\/screenshots\/13\/full\/21.jpg","args":[],"viewport":{"width":1400,"height":1080},"fullPage":true,"waitUntil":"networkidle0"}}'" failed.

Exit Code: 1(General error)
```

I've followed the instructions from the readme for installing the latest version of stable Chrome:

```
curl -sL https://deb.nodesource.com/setup_8.x | sudo -E bash -
sudo apt-get install -y nodejs gconf-service libasound2 libatk1.0-0 libc6 libcairo2 libcups2 libdbus-1-3 libexpat1 libfontconfig1 libgcc1 libgconf-2-4 libgdk-pixbuf2.0-0 libglib2.0-0 libgtk-3-0 libnspr4 libpango-1.0-0 libpangocairo-1.0-0 libstdc++6 libx11-6 libx11-xcb1 libxcb1 libxcomposite1 libxcursor1 libxdamage1 libxext6 libxfixes3 libxi6 libxrandr2 libxrender1 libxss1 libxtst6 ca-certificates fonts-liberation libappindicator1 libnss3 lsb-release xdg-utils wget
sudo npm install --global --unsafe-perm puppeteer
sudo chmod -R o+rx /usr/lib/node_modules/puppeteer/.local-chromium
```

I've tried specifying custom node and npm binaries.  I've also tried a custom include path.

My code looks like this:

```
Browsershot::url($this->url)
            ->windowSize($this->width, 1080)
            ->fullPage()
            ->waitUntilNetworkIdle()
            ->save($save_path_local);
```

I'm actually installing puppeteer locally as part of my build process in Forge.  I set that up before I saw the above instructions for installing Chrome in the readme.  Not sure if that makes any difference?

Laravel v5.7.11
Browsershot v3.26

I'm just not sure how to interpret that error.  Any ideas?

Thanks!

**Comment by shradhabanerjee** [comment]
@peteheaney , Were you able to resolve this issue? If yes, what is the solution, I am facing the same issue from long time. Thanks !

**Comment by petehjfd** [comment]
Hi @shradhabanerjee No I'm afraid not.  I've also posted the issue on [Stack Overflow](https://stackoverflow.com/questions/54399750/error-when-using-browsershot-with-laravel-on-forge-provisioned-server), but I've had no response there either.

And I've obviously had no reply from @spatie.  I think they may have abandoned this package.

**Comment by shradhabanerjee** [comment]
Hi @petehjfd ,

I was able to resolve this issue with `npm install` in the root folder of my project. 

Below is the error stack trace I had,

`local.ERROR: The command "PATH=$PATH:/usr/local/bin NODE_PATH=`npm root -g` node '/Library/WebServer/Documents/project/vendor/spatie/browsershot/src/../bin/browser.js' '{"url":"file:\/\/\/var\/tmp\/0183143001549972722\/index.html","action":"pdf","options":{"path":"\/Library\/WebServer\/Documents\/project\/public\/invoices\/Bill Oct 2018.pdf","args":[],"viewport":{"width":800,"height":600},"displayHeaderFooter":false,"waitUntil":"networkidle0"}}'" failed.`

Exit Code: 1(General error)

Working directory: /Library/WebServer/Documents/project/public

Output:
================

Error Output:
================
internal/modules/cjs/loader.js:611
    throw err;
    ^
Error: Cannot find module 'puppeteer'

**Comment by petehjfd** [comment]
Hi @shradhabanerjee 

Thanks for your reply.  Unfortunately it looks like our issues are different. I already have puppeteer installed in the root folder.

My Error Output says

`Error: ENOENT: no such file or directory, open '/home/forge/my-app.co.uk/storage/screenshots/27/full/45.jpg'`

The reason it can't find the file is because it doesn't exist because it was supposed to have been created by Browsershot, but it hasn't.

**Comment by petehjfd** [comment]
@shradhabanerjee Sorry, I've just realised I'm posting with the wrong account.  @petehjfd and @peteheaney are both me.

**Comment by shradhabanerjee** [comment]
Hi @peteheaney, thats ok, I'd realised its the person :)

Anyways, after `npm install` in my project folder, I even got the error like you. So I created an empty directory.

The error looks like below (similar to your's):

`[2019-02-12 12:22:59] local.ERROR: The command "PATH=$PATH:/usr/local/bin NODE_PATH=`npm root -g` node '/Library/WebServer/Documents/project/vendor/spatie/browsershot/src/../bin/browser.js' '{"url":"file:\/\/\/var\/tmp\/0136191001549974172\/index.html","action":"pdf","options":{"path":"\/Library\/WebServer\/Documents\/project\/public\/invoices\/Bill Oct 2018.pdf","args":[],"viewport":{"width":800,"height":600},"displayHeaderFooter":false,"waitUntil":"networkidle0"}}'" failed.`

`Exit Code: 1(General error)`

`Working directory: /Library/WebServer/Documents/project/public`

`Output:`
`================`


`Error Output:`
`================`
`{ Error: ENOENT: no such file or directory, open` `'/Library/WebServer/Documents/project/public/invoices/h1-1 Oct 2018.pdf'`

I added the directory, `invoices` manually. That worked for me.

*Tip:* Also added .gitkeep file in that folder, pushed the empty directory to remote so that this doesn't happen again.
