### ISSUE TITLE
Node path error

### ISSUE THREAD

**Issue by MusabAkram** [spatie/browsershot#289]
BrowserShot works fine when i'm working locally but when i test it on my sever it gives me following error:
**The command "PATH=$PATH:/usr/local/bin NODE_PATH=`npm root -g` node '/var/app/current/vendor/spatie/browsershot/src/../bin/browser.js' '{"url":"file:\/\/\/tmp\/0911479001557472350\/index.html","action":"screenshot","options":{"type":"png","path":"promoMobile.png","args":[],"viewport":{"width":360,"height":750},"displayHeaderFooter":false}}'" failed.**

i have tried the solutions for the issues #137, #243 and #262 but nothing worked for me.

- Changed path of save image to relative path
- Tried changing '$PATH:/usr/local/bin' => '$PATH:/usr/bin'
- Installed node again on server and updated its version

**Comment by sitte** [comment]
I have, I think the same error. If I enable php errors I have additional:
Fatal error</b>:   in <b>/var/www/html/src/Browsershot.php</b> on line <b>606</b><br />

Any ideas?

**Comment by sitte** [comment]
When I tried to execute this command via bash and looked into logs I found info that root user cannot run chromium in sandbox. So I added ->noSandbox to browsershot execution and that works. 

```
Browsershot::url('http://legionhdk.pl/images/leg/szablony/4/index_1548173420.html')
    ->windowSize(1200, 628)
    ->noSandbox()
    ->save($pathToImage);
```

**Comment by danhunsaker** [comment]
If PHP is running as root (which is the only way it will start other processes - such as Node - as root, too), you have major problems with your server configuration. Specifically, _a massive security hole for attackers to break in and completely destroy your system_. Ensure your PHP service is running as an unprivileged user!

However. From what I see here, the real problem is permitting root login to your server, which is needed to run PHP's CLI SAPI as root. This is also a security hole, and generally a bad idea - always create an unprivileged user with `sudo` access for day-to-day activities (such as running the PHP CLI SAPI), and disable root logins.

All that said, it sounds like a different problem related to sandboxing is your real culprit. Comment out the line that disables the sandbox, then rerun your test(s) as the web server user (`sudo -u www-data {command}`) to see what information you get back from that.

**Comment by atymic** [comment]
@MusabAkram 
Did you manage to solve your issue?

**Comment by mathiasonea** [comment]
@MusabAkram do you have PHP running in a docker container? Does the container know where to find the node binary?

**Comment by okaufmann** [comment]
Had the same Problem. As I'm using fnm the binary was in another path

    which node # result /var/folders/j8/tnrq90293tq8vzptb9_tz7pr0000gn/T/fnm-shell-6891140/bin/node

After I set this url as node binary it worked:

    Spatie\Browsershot\Browsershot::url(
        'https://google.com'
    )
        ->setNodeBinary(
            '/var/folders/j8/tnrq90293tq8vzptb9_tz7pr0000gn/T/fnm-shell-6891140/bin/node'
        )
        ->windowSize(1200, 628)
        ->noSandbox()
        ->save('test.png');
