### ISSUE TITLE
Event hooks

### ISSUE THREAD

**Issue by brendt** [spatie/browsershot#329]
An issue came up on the crawler package, which could be easily solved if browsershot supported some kind of event hooks: https://github.com/spatie/crawler/issues/257

What about something like this?

```php
Browsershot::html('')
    ->on(Browsershot::EVENT_AFTER_JAVASCRIPT, function (/* … */) {
        // …
    });
```

A few thoughts coming to mind:

- Since this package basically consists of one class, it makes sense to add the event handling logic on it. On the other hand, it will only make this class even bigger. What are the opinions on this?
- `Browsershot::EVENT_AFTER_JAVASCRIPT` or `BrowsershotEvent::AFTER_JAVASVCRIPT` or something else?
- Are there any more places where these kind of hooks make sense? Should we add it if there's only one use case we can think of right now? (https://github.com/spatie/crawler/issues/257)

@Gummibeer @freekmurze @riasvdv I'd like to hear your opinion.

**Comment by Gummibeer** [comment]
Could it be an idea to even refactor the `command` methods into a dedicated `BrowsershotCommand` class which provides a `__toString()` method and a dynamic builder?
The idea behind would be to slim down the main class at all and don't have only the events moving out.

For the events - @brendt I'm surprised you don't want to use https://github.com/spatie/enum for it 😉😅
Just kidding, but could be an idea to typecast the event.

At all I'm for it - I've introduced the request. 🙈 

But I'm not happy with the naming. The browser has no `after_js` event. So it will be more something like `onNetworkIdle()` as the base for it? 🤔 In this case it should be named. Because JS ist running "forever" in a page.

**Comment by brendt** [comment]
Sidenote, could `waitForFuntion` be of any help? 

https://github.com/spatie/browsershot#waiting-for-javascript-function

**Comment by Gummibeer** [comment]
My first try didn't work. But could be that something like `$('body').scrollTo(100);` doesn't return `true` and that's why it timed out. 🤔

**Comment by Gummibeer** [comment]
@brendt does anyone want to proceed here?

PS: I wish you a happy new year! A great year with your new 👶 and I hope that we will keep up the good work together! 👨‍💻And looking forward to LaraconEU.

**Comment by brendt** [comment]
Hi Tom, thanks! We don't have any real use cases for this ourselves, which is why the issue has been neglected, I'll reopen it though, we might come back to it at a later date.
