### ISSUE TITLE
The command "node ^"C:^\xampp^\htdocs^\test^\vendor^\.....

### ISSUE THREAD

**Issue by nguyentrongchinh1997** [spatie/browsershot#384]
Help me. How to fix?

The command "node ^"C:^\xampp^\htdocs^\test^\vendor^\spatie^\browsershot^\src/../bin/browser.js^" ^"^{^\^"url^\^":^\^"https:^\/^\/example.com^\^",^\^"action^\^":^\^"screenshot^\^",^\^"options^\^":^{^\^"type^\^":^\^"png^\^",^\^"path^\^":^\^"C:^\^\xampp^\^\htdocs^\^\test^\^\public^\^\saves^\^\chinh.png^\^",^\^"args^\^":^[^],^\^"viewport^\^":^{^\^"width^\^":640,^\^"height^\^":480^}^}^}^"" failed. Exit Code: 1(General error) Working directory: C:\xampp\htdocs\test\public Output: ================ Error Output: ================ internal/modules/cjs/loader.js:985 throw err; ^ Error: Cannot find module 'puppeteer' Require stack: - C:\xampp\htdocs\test\vendor\spatie\browsershot\bin\browser.js at Function.Module._resolveFilename (internal/modules/cjs/loader.js:982:15) at Function.Module._load (internal/modules/cjs/loader.js:864:27) at Module.require (internal/modules/cjs/loader.js:1044:19) at require (internal/modules/cjs/helpers.js:77:18) at Object.<anonymous> (C:\xampp\htdocs\test\vendor\spatie\browsershot\bin\browser.js:1:19) at Module._compile (internal/modules/cjs/loader.js:1158:30) at Object.Module._extensions..js (internal/modules/cjs/loader.js:1178:10) at Module.load (internal/modules/cjs/loader.js:1002:32) at Function.Module._load (internal/modules/cjs/loader.js:901:14) at Function.executeUserEntryPoint [as runMain]

**Comment by nickorsk2017** [comment]
Same problem

**Comment by damonbakker** [comment]
I have also been stuck on the same problem for around 2 days now. 
I am running windows 10 with xampp, php 7.3

This also happens when you use setNodeModulePath() (with double quotes) to make sure the module exists. I had to make a symlink to my node directory cause spaces didn't work. But I doubt that has anything to do with it
It's probably something specific to windows.

For me, installing the puppeteer to the local npm_modules inside my laravel project made that error go away. But then I encounter another problem:

`TimeoutError: waiting for target failed: timeout 30000ms exceeded`
```
node_modules\puppeteer\lib\Launcher.js:247:21)
    at process._tickCallback (internal/process/next_tick.js:68:7) name: 'TimeoutError' }
openssl config failed: error:02001002:system library:fopen:No such file or directory
```
Then you can get rid of that by `set OOPENSSL_CONF=` in powershell.

But now I just have a regular timeout at the node.exe process 
```
^"^{^\^"url^\^":^\^"http:^\/^\/example.com^\^",^\^"action^\^":^\^"content^\^",^\^"options^\^":^{^\^"args^\^":^[^],^\^"viewport^\^":^{^\^"width^\^":800,^\^"height^\^":600^}^}^}^"" exceeded the timeout of 60 seconds
```

I have looked into the troubleshooting issue of disabled extensions, but both the embedded chromium and my own chrome --headless (tried both for browsershot) work normally if I manually call them to perform some operations using --disabled-extensions turned on.

But through somehow I can't get it to work through this library. 
I might look at browsershot v2 in the meanwhile.

Maybe someone else can see what's the solution in this niche scenario, I am gonna take a small break from this.

**Comment by damonbakker** [comment]
In another library it seems like '--no-sandbox' as an argument for puppeteer fixed the same type of error.
It's unsafe for arbitrary html content, but maybe there is a way to pass this to puppeteer in your use case and see if it changes anything?

**Comment by extrem7** [comment]
I have the same error:
The command "PATH=$PATH:/usr/local/bin NODE_PATH=`npm root -g` node '/var/www/www-root/data/www/localhost/vendor/spatie/browsershot/src/../bin/browser.js' '{"url":"https:\/\/github.com\/extrem7?tab=repositories","action":"pdf","options":{"path":"\/var\/www\/www-root\/data\/www\/localhost\/public\/manager.pdf","args":[],"viewport":{"width":800,"height":600}}}'" failed. Exit Code: 127(Command not found) Working directory: /var/www/www-root/data/www/localhost/public Output: ================ Error Output: ================ sh: npm: command not found sh: node: command not found

**Comment by jmslbam** [comment]
I symlinked my node and npm that I installed via NVM to my `/usr/local/bin` directory because there where none. 

And otherwise you can try to use on of these settings https://github.com/spatie/browsershot#custom-node-and-npm-binaries

The error says that it can't find `npm` and `node`. Browsershot excecutes a terminal command via PHP. In your case because you are on windows it calls `escapeshellcmd`.

So find out on your windows installtion in which path your `node` is installed and make sure that browsershot is able to find it. 
Or make sure that when Browsershot calls run the command `node` that it's available. This is a configuration issue on our local machines and not a specific issue for Browsershot.

Hope this information helps!

**Comment by freekmurze** [comment]
Thanks for answering this one @jmslbam
