### ISSUE TITLE
CSS in headerHtml not working

### ISSUE THREAD

**Issue by schmidfelix** [spatie/browsershot#442]
I'm trying to set a custom header and footer in my PDF generation, but the TailwindCSS classes don't get applied.

Code used to generate the pdf:
```php
Browsershot::html(view('body', [
            'data' => $data,
        ])->render())
            ->showBackground()
            ->format('A4')
            ->emulateMedia("screen")
            ->showBrowserHeaderAndFooter()
            ->headerHtml(view('header')->render())
            ->margins(50,0, 0, 0)
            ->savePdf(public_path('invoice.pdf'));
```

My header html file:
```html
<div class="font-sans text-gray-900 antialiased">
    <div class="bg-blue-600 py-3 px-20 flex w-100 justify-between items-center">
        <h2 class="text-2xl text-white">Title</h2>
        <h3 class="text-md text-gray-200 uppercase">Text</h3>
    </div>
</div>
```

It adds the text "Title" and "Text", but very small and without the blue background:
<img width="1199" alt="Bildschirmfoto 2020-11-08 um 22 03 42" src="https://user-images.githubusercontent.com/22103266/98484233-4f48f500-220e-11eb-81e2-c9d24d6186e3.png">
When I try to add my stylesheet via a html->head->link tag, I't always times out.
And when adding my header html code to my pdf "body/content" view everything works fine.

How can I fix it? Have i missed something in the documentation?

**Comment by ahoiroman** [comment]
Got the same issue and still no solution.

If you paste raw css to your header-blade-stuff, this will render as expected. 

But:

- At the moment is it not possible to add something like `<link href="{{ asset(mix('/css/app.css')) }}" rel="stylesheet">` to the header's blade-file, as it is going to timeout
- You even can not grab the css and paste between style-tags, because you are going to receive `escapeshellarg(): Argument exceeds the allowed length of 2097152 bytes`
